version: "3.8"

services:
  # PostgreSQL database for Keycloak's internal data
  keycloak-postgres:
    image: postgres:16-alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD:-keycloak_changeme}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "${KC_DB_PORT:-5433}:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - obp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL database for OBP user federation
  user-storage-postgres:
    image: postgres:16-alpine
    container_name: user-storage-postgres
    environment:
      POSTGRES_DB: ${USER_STORAGE_DB_NAME:-obp_mapped}
      POSTGRES_USER: ${USER_STORAGE_DB_USER:-obp}
      POSTGRES_PASSWORD: ${USER_STORAGE_DB_PASSWORD:-changeme}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "${USER_STORAGE_DB_PORT:-5434}:5432"
    volumes:
      - user_storage_postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - obp-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${USER_STORAGE_DB_USER:-obp} -d ${USER_STORAGE_DB_NAME:-obp_mapped}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak with OBP User Storage Provider (Runtime Configuration)
  keycloak:
    image: obp-keycloak-provider:latest
    container_name: obp-keycloak
    depends_on:
      keycloak-postgres:
        condition: service_healthy
      user-storage-postgres:
        condition: service_healthy
    environment:
      # Keycloak Admin Configuration
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}

      # Keycloak's internal database configuration
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL:-jdbc:postgresql://keycloak-postgres:5432/keycloak}
      KC_DB_USERNAME: ${KC_DB_USERNAME:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-keycloak_changeme}

      # OBP User Storage database configuration (Cloud-Native)
      DB_URL: jdbc:postgresql://user-storage-postgres:5432/${USER_STORAGE_DB_NAME:-obp_mapped}
      DB_USER: ${USER_STORAGE_DB_USER:-obp}
      DB_PASSWORD: ${USER_STORAGE_DB_PASSWORD:-changeme}
      DB_DRIVER: org.postgresql.Driver
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      # Hibernate Configuration for User Storage
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO:-validate}
      HIBERNATE_SHOW_SQL: "${HIBERNATE_SHOW_SQL:-true}"
      HIBERNATE_FORMAT_SQL: "${HIBERNATE_FORMAT_SQL:-true}"

      # Keycloak Configuration
      KC_HOSTNAME_STRICT: "${KC_HOSTNAME_STRICT:-false}"
      KC_HOSTNAME_STRICT_HTTPS: "${KC_HOSTNAME_STRICT_HTTPS:-false}"
      KC_HTTP_ENABLED: "${KC_HTTP_ENABLED:-true}"
      KC_HEALTH_ENABLED: "${KC_HEALTH_ENABLED:-true}"
      KC_METRICS_ENABLED: "${KC_METRICS_ENABLED:-true}"
      KC_FEATURES: "${KC_FEATURES:-token-exchange}"
    ports:
      - "${KEYCLOAK_HTTP_PORT:-8000}:8080"
      - "${KEYCLOAK_HTTPS_PORT:-8443}:8443"
    networks:
      - obp-network
    volumes:
      # Optional: Custom themes (if using themed build)
      - ./themes:/opt/keycloak/themes
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  # Optional: Admin tool for Keycloak PostgreSQL
  keycloak-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: keycloak-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${KEYCLOAK_PGADMIN_EMAIL:-keycloak-admin@obp.com}
      PGADMIN_DEFAULT_PASSWORD: ${KEYCLOAK_PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${KEYCLOAK_PGADMIN_PORT:-5051}:80"
    depends_on:
      - keycloak-postgres
    networks:
      - obp-network
    restart: unless-stopped
    profiles:
      - tools

  # Optional: Admin tool for User Storage PostgreSQL
  user-storage-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: user-storage-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${USER_STORAGE_PGADMIN_EMAIL:-user-storage-admin@obp.com}
      PGADMIN_DEFAULT_PASSWORD: ${USER_STORAGE_PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${USER_STORAGE_PGLADMIN_PORT:-5050}:80"
    depends_on:
      - user-storage-postgres
    networks:
      - obp-network
    restart: unless-stopped
    profiles:
      - tools

volumes:
  keycloak_postgres_data:
    driver: local
  user_storage_postgres_data:
    driver: local

networks:
  obp-network:
    driver: bridge
# Example usage:
#
# 1. Development with default values:
#    docker-compose -f docker-compose.runtime.yml up
#
# 2. Production with environment file:
#    docker-compose -f docker-compose.runtime.yml --env-file .env.prod up
#
# 3. With pgAdmin tools:
#    docker-compose -f docker-compose.runtime.yml --profile tools up
#
# 4. Kubernetes-style with individual env vars:
#    KC_DB_PASSWORD=secure_keycloak_pass \
#    USER_STORAGE_DB_PASSWORD=secure_user_pass \
#    KEYCLOAK_ADMIN_PASSWORD=secure_admin_pass \
#    docker-compose -f docker-compose.runtime.yml up
#
# 5. With custom database hosts (external databases):
#    KC_DB_URL=jdbc:postgresql://external-keycloak-db:5432/keycloak \
#    DB_URL=jdbc:postgresql://external-user-db:5432/obp_mapped \
#    docker-compose -f docker-compose.runtime.yml up keycloak
#
# 6. Production deployment with separate database hosts:
#    docker-compose -f docker-compose.runtime.yml up keycloak \
#      -e KC_DB_URL="jdbc:postgresql://keycloak-prod-db:5432/keycloak" \
#      -e DB_URL="jdbc:postgresql://user-storage-prod-db:5432/obp_mapped"
#
# Environment Variables:
# Keycloak Database:
#   KC_DB_NAME=keycloak
#   KC_DB_USERNAME=keycloak
#   KC_DB_PASSWORD=keycloak_changeme
#   KC_DB_PORT=5433 (external port for Keycloak's internal database)
#
# User Storage Database:
#   USER_STORAGE_DB_NAME=obp_mapped
#   USER_STORAGE_DB_USER=obp
#   USER_STORAGE_DB_PASSWORD=changeme
#   USER_STORAGE_DB_PORT=5434 (changed from 5432 to avoid conflicts)
#
# Keycloak Configuration:
#   KEYCLOAK_ADMIN=admin
#   KEYCLOAK_ADMIN_PASSWORD=admin
#   KEYCLOAK_HTTP_PORT=8000
#   KEYCLOAK_HTTPS_PORT=8443
