-- =============================================================================
-- User Storage Database Setup Script
-- =============================================================================
-- This script sets up the user storage database components for OBP Keycloak Provider.
-- This should be run on your existing OBP database to enable OIDC user federation.
--
-- IMPORTANT: This file references the official OBP-API SQL scripts as the source of truth.
-- Please use the scripts from the official OBP-API repository instead of duplicating code here.
--
-- Usage:
--   1. Clone or download the OBP-API repository
--   2. Navigate to: obp-api/src/main/scripts/sql/OIDC/
--   3. Follow the instructions in the README.md file in that directory
--
-- Source Repository:
--   https://github.com/OpenBankProject/OBP-API/tree/develop/obp-api/src/main/scripts/sql/OIDC
--
-- Environment Variables Referenced:
--   DB_USER (default: oidc_user)
--   DB_PASSWORD (set in your .env file)
--   DB_NAME (default: obp_mapped)
--   DB_AUTHUSER_TABLE (default: v_oidc_users)
-- =============================================================================

-- FOR KEYCLOAK USER FEDERATION:
--
-- To set up read access to users for Keycloak, run the following from the OBP-API repository:
--
-- cd obp-api/src/main/scripts/sql/OIDC/
-- psql -d your_obp_database
-- \i give_read_access_to_users.sql
--
-- This will:
-- 1. Create the oidc_user role with appropriate permissions
-- 2. Create the v_oidc_users view joining authuser and resourceuser tables
-- 3. Grant SELECT permissions on the view to the oidc_user
--
-- The official scripts include:
-- - set_and_connect.sql: Variable definitions and database connection
-- - cre_OIDC_USER.sql: Creates the OIDC user with limited privileges
-- - cre_v_oidc_users.sql: Creates the v_oidc_users view with proper security
-- - give_read_access_to_users.sql: Main script that orchestrates the setup
--
-- SECURITY NOTES:
-- - The view only exposes validated users (au.validated = true)
-- - The oidc_user has minimal read-only permissions
-- - Password hashes are included for credential verification (ensure secure access)
--
-- For additional OIDC setup scripts (clients, admin access), see:
-- https://github.com/OpenBankProject/OBP-API/tree/develop/obp-api/src/main/scripts/sql/OIDC

SELECT 'Please use the official OBP-API SQL scripts for OIDC setup.' AS message,
       'Repository: https://github.com/OpenBankProject/OBP-API/tree/develop/obp-api/src/main/scripts/sql/OIDC' AS source,
       'This avoids code duplication and ensures you have the latest version.' AS reason;
